---
- name: Install required packages
  ansible.builtin.package:
    name: "{{ geo2drop_packages }}"
    state: present

- name: Ensure nftables is enabled and running
  ansible.builtin.systemd:
    name: nftables
    state: started
    enabled: true
  when: geo2drop_manage_nftables | bool
