---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart geo2drop timer
  ansible.builtin.systemd:
    name: geo2drop.timer
    state: restarted
    enabled: true