---
- name: Reload firewalld
  ansible.builtin.command:
    cmd: firewall-cmd --reload
  changed_when: true

- name: Restart firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart geo2drop timer
  ansible.builtin.systemd:
    name: geo2drop.timer
    state: restarted
    enabled: true
